name: Deploy backend

on:
    push:
        branches: ["main"]

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.16.0

            - name: Install backend deps
              working-directory: ./backend
              run: npm install --production

            - name: Deploy backend
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ~/apps/url-backend
                      git pull origin main
                      cd backend
                      npm install --production
                      npm run bild
                      pm2 restart url-backend || pm2 start dist/index.js --name url-backend
